config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  namespace :admin do
    resources :categories, only: [:index, :create, :destroy]
    resources :users, only: [:index, :new, :create, :show, :destroy]
  end
  root to: 'posts#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates :content, presence: true
  validates :post, presence: true
  validates :user, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories

  validates :title, presence: true
  validates :content, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '64x64>' }, default_url: ":style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_admin

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path, notice: 'Category successfully created.'
    else
      redirect_to admin_categories_path, alert: 'Category is not created.'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path, notice: 'Category successfully deleted.'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def check_admin
    unless current_user&.admin?
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.skip_confirmation!

    if @user.save
      redirect_to admin_users_path, notice: 'User successfully created.'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'User successfully deleted.'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
  end

  def check_admin
    unless current_user&.admin?
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user|
      user.permit(:email, :password, :remember_me)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation, :avatar)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :destroy]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @post.comments << @comment

    if @comment.save
      redirect_to @post, notice: 'Comment successfully created.'
    else
      redirect_to @post, alert: 'Comment not created.'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])

    if current_user.admin? or current_user == @comment.user
      @comment.destroy
      redirect_to @post, notice: 'Comment successfully deleted.'
    else
      redirect_to @post, alert: 'You can\'t delete this comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :check_permissions, only: [:edit, :destroy]

  def index
    if params[:category_id].present?
      @posts = Category.find(params[:category_id]).posts
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post successfully updated.'
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])

    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: 'Post successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_ids=>[])
  end

  def check_permissions
    @post = Post.find(params[:id])
    unless current_user.admin? or current_user == @post.user
      redirect_to post_path(@post), alert: 'You can\'t edit not your own posts.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<h2>New category</h2>
<%= simple_form_for Category.new, url: {controller: :categories, action: :create} do |f| %>
  <div class="form_inputs">
    <%= f.input :name, as: :text, placeholder: 'Name' %>
    <%= f.button :submit, 'Create category' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit post</h1>
<%= simple_form_for @post do |f| %>
  <div class="form-inputs">
    <%= f.input :title, placeholder: 'Enter title' %>
    <%= f.input :content, as: :text, placeholder: 'Content' %>
    <% Category.all.each do |category| %>
      <%= check_box_tag "post[category_ids][]", category.id, @post.category_ids.include?(category.id) %>
      <%= category.name %>
      <br/>
    <% end %>
  </div>
  <%= f.button :submit, 'Update post' %>
  <%= link_to 'Cancel', post_path(@post), class: 'btn btn-danger' %>
<% end %>

app/views/admin/categories/index.html.erb
<%= render partial: 'form' %>

<table class="table">
  <thead>
    <th>id</th>
    <th>name</th>
  </thead>
  <tbody>

    <% @categories.each do |category| %>
      <tr>
        <td>
          <%= category.id %>
        </td>
        <td>
          <%= category.name %>
        </td>
        <td>
          <%= category.created_at.localtime.strftime("%m/%d/%Y at %I:%M%p") %>
        </td>
        <td>
          <%= link_to '', admin_category_path(category), method: :delete, class: 'glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/_form.html.erb
<%= simple_form_for @user, url: admin_users_path, method: :post do |f| %>
  <%= f.input :name, placeholder: 'Name' %>
  <%= f.input :email, placeholder: 'Email' %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :role, collection: User.roles.keys, prompt: 'Select role' %>
  <br/>
  <%= f.button :submit, 'Create user' %>
<% end %>

app/views/admin/users/index.html.erb
<br/>
<%= button_to 'New user', new_admin_user_path, method: :get, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <th>id</th>
    <th>name</th>
    <th>email</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.id, admin_user_path(user) %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= link_to '', admin_user_path(user), method: :delete, class: 'glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h3>User info</h3>
<table class="table">
  <thead>
    <th>id</th>
    <th>username</th>
    <th>email</th>
    <th>last sign in</th>
    <th>role</th>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= @user.id %>
      </td>
      <td>
        <%= @user.name %>
      </td>
      <td>
        <%= @user.email %>
      </td>
      <td>
        <%= @user.last_sign_in_at.localtime.strftime("%m/%d/%Y at %I:%M%p") %>
      </td>
      <td>
        <%= @user.role %>
      </td>
    </tr>
  </tbody>
</table>
<h3>Posts:</h3>
<table class="table">
  <thead>
    <th>post_id</th>
    <th>title</th>
    <th>created_at</th>
    <th>updated_at</th>
  </thead>
  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.id, post_path(post.id) %>
        </td>
        <td>
          <%= post.title %>
        </td>
        <th>
          <%= post.created_at.localtime.strftime("%m/%d/%Y at %I:%M%p") %>
        </th>
        <th>
          <%= post.updated_at.localtime.strftime("%m/%d/%Y at %I:%M%p") %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>Comments:</h3>
<table class="table">
  <thead>
    <th>comment_id</th>
    <th>content</th>
    <th>post_id</th>
    <th>created_at</th>
  </thead>
  <tbody>
    <% @user.comments.each do |comment| %>
      <tr>
        <td>
          <%= comment.id %>
        </td>
        <td>
          <%= comment.content  %>
        </td>
        <td>
          <%= comment.post_id %>
        </td>
        <td>
          <%= comment.created_at.localtime.strftime("%m/%d/%Y at %I:%M%p") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>Actions:</h3>
<%= link_to 'DELETE THIS USER', admin_user_path(@user), method: :delete %>

app/views/comments/_form.html.erb
<h2>Add comment
  <%= simple_form_for [@post, @post.comments.build] do |f| %>
    <div class="form-inputs">
      <%= f.input :content, as: :text, placeholder: 'Content' %>
      <%= f.button :submit, 'Create comment' %>
    </div>
  <% end %>
</h2>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <%= link_to 'Edit account', edit_user_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'navbar-brand' %>
  <p class="navbar-brand">
    <%= "Hello, #{current_user.email}" %>
  </p>
<% else %>
  <%= link_to new_user_session_path, class: 'navbar-brand' do %>
    <span class="glyphicon glyphicon-log-in"></span>
    Sign in
  <% end %>
  <%= link_to  new_user_registration_path, class: 'navbar-brand' do %>
    <span class="glyphicon glyphicon-user"></span>
    Sign up
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <span class="glyphicon glyphicon-home"></span>
        Home
      <% end %>
      <%= render 'layouts/nav_links_for_auth' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title>
      <%= content_for?(:title) ? yield(:title) : 'Blog' %>
    </title>
    <meta content="<%= content_for?(:description) ? yield(:description) : 'Blog' %>" name="description"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <hr>
    <footer>
      Copyright Best Blog in the World 2017
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<h3>About the Website</h3>
<p>
  This web application was created with
  <%= link_to('Rails', 'http://rubyonrails.org/') %>
  from the <%= link_to('Rails project', 'https://github.com/rails/rails') %>.
</p>

app/views/posts/_categories.html.erb
<div class="well">
  <h4>Categories</h4>
  <div class="row">
    <div class="col-lg-6">
      <ul class="list-unstyled">
        <% Category.all.each do |category| %>
          <li>
            <%= link_to category.name, posts_path(category_id: category.id) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/_comments.html.erb
<div class="comments">
  <% if @post.comments.empty? %>
    <p>
      <%= 'No comments yet... so you can be the first!' %>
    </p>
    <br/>
  <% else %>
    <% @post.comments.each do |comment| %>
      <div class="media">
        <div class="pull-left">
          <img class="media-object">
            <%= image_tag comment.user.avatar.url(:thumb) %>
          </img>
        </div>
        <div class="media-body">
          <h5 class="media-heading glyphicon glyphicon-time"></h5>
          <%= " #{comment.created_at.localtime.strftime("%d/%m/%Y at %I:%M%p")} by #{comment.user.name}" %>
          <% if current_user&.admin? or current_user == comment.user %>
            <%= link_to '', post_comment_path(@post, comment), method: :delete, class: 'glyphicon glyphicon-remove' %>
          <% end %>
          <p>
            <%= comment.content %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_post_actions.html.erb
<hr/>
<% if current_user&.admin? or current_user == @post.user %>
  <%= link_to 'Edit post', edit_post_path(@post), class: 'btn btn-warning' %>
  <%= link_to 'Delete post', post_path(@post), method: :delete, class: 'btn btn-danger' %>
<% end %>

app/views/posts/_post_base.html.erb
<h1>
  <%= h(@post.title) %>
</h1>
<div class="glyphicon glyphicon-time"></div>
<%= "Posted on #{@post.created_at.localtime.strftime("%d/%m/%Y at %I:%M%p")} by"  %>
<b>
  <%= @post.user.name %>
</b>
<hr/>
<p class="lead">
  <%= @post.content %>
</p>

app/views/posts/_posts_preview.html.erb
<% @posts.each do |post| %>
  <h2>
    <%= link_to h(post.title), post %>
  </h2>
  <% post.categories.each do |category| %>
    <span>
      <%= "##{category.name}" %>
    </span>
  <% end %>
  <p>
    <span class="glyphicon glyphicon-time"></span>
    <%= " Posted on #{post.created_at.localtime.strftime("%d/%m/%Y at %I:%M%p")} by" %>
    <b>
      <%= post.user.name %>
    </b>
    <!-- image
    -->
  </p>
  <%= truncate(post.content, length:100, separator: ' ') { link_to ('Read more <span class="glyphicon glyphicon-chevron-right"></span>').html_safe, post, class: 'btn btn-default' } %>
<% end %>

app/views/posts/_search.html.erb
<div class="well">
  <h4>Search</h4>
  <div class="input-group">
    <input class="form-control" type="text">/</input>
    <span class="input-group-btn">
      <button class="btn-btn-default" type="button">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
</div>

app/views/posts/_side_widget.html.erb
<div class="well">
  <h4>Create your own post</h4>
  <p>
    <%= link_to 'New post', new_post_path, class: 'btn btn-default' %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= simple_form_for @post do |f| %>
  <div class="form-inputs">
    <%= f.input :title, placeholder: 'Enter title' %>
    <%= f.input :content, as: :text, placeholder: 'Content' %>
  </div>
  <%= f.button :submit, 'Update post' %>
  <%= link_to 'Cancel', post_path(@post), class: 'btn btn-danger' %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <!-- Blog Entries Column
    -->
    <div class="col-md-8">
      <h1 class="page-header">
        Blog
        <small>Best Blog in the World!</small>
      </h1>
      <!-- posts
      -->
      <%= render partial: 'posts_preview' %>
      <!-- Pagination
      -->
      <ul class="pager">
        <li class="previous">
          <a href="#">Prev</a>
        </li>
        <li class="next">
          <a href="#">Next</a>
        </li>
      </ul>
    </div>
    <div class="col-md-4">
      <%= render partial: 'search' %>
      <%= render partial: 'categories' %>
      <%= render partial: 'side_widget' %>
    </div>
    <hr/>
    <!-- Footer
    -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright Best Blog in the World! 2017</p>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create new Post</h1>
<%= simple_form_for @post do |f| %>
  <div class="form-inputs">
    <%= f.input :title, placeholder: 'Enter title' %>
    <%= f.input :content, as: :text, placeholder: 'Content' %>
  </div>
  <%= f.button :submit, 'Create post' %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <%= render partial: 'post_actions' %>
      <%= render partial: 'post_base' %>
      <hr/>
      <%= render partial: 'comments' %>
      <br/>
      <div class="well">
        <h4>Leave a Comment:</h4>
        <%= render partial: '/comments/form' %>
      </div>
      <hr/>
    </div>
    <!-- Blog Sidebar Widgets Column-->
    <div class="col-md-4">
      <%= render partial: 'search' %>
      <%= render partial: 'categories' %>
      <%= render partial: 'side_widget' %>
    </div>
  </div>
</div>